// example/src/components/ChatWindow.tsx
import { useQuery, useMutation } from "convex/react";
import React, { useState, useRef, useCallback, useEffect } from "react";
import { useWindowSize } from "@/lib/utils";
import MessageItem from "./MessageItem";
import { ServerMessage } from "./ServerMessage";
import { api } from "../../convex/_generated/api";

export default function ChatWindow() {
  const [drivenIds, setDrivenIds] = useState<Set<string>>(new Set());
  const [isStreaming, setIsStreaming] = useState(false);
  const messages = useQuery(api.messages.listMessages);
  const [inputValue, setInputValue] = useState("");
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const messageContainerRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const clearAllMessages = useMutation(api.messages.clearMessages);

  const focusInput = useCallback(() => {
    inputRef.current?.focus();
  }, []);

  const scrollToBottom = useCallback(
    (behavior: ScrollBehavior = "smooth") => {
      if (messagesEndRef.current) {
        messagesEndRef.current.scrollIntoView({ behavior });
      }
    },
    [messagesEndRef],
  );

  const windowSize = useWindowSize();

  useEffect(() => {
    scrollToBottom();
  }, [windowSize, scrollToBottom]);

  const sendMessage = useMutation(api.messages.sendMessage);

  if (!messages) return null;

  return (
    <div className="flex-1 flex flex-col h-full bg-white">
      <div
        ref={messageContainerRef}
        className="flex-1 overflow-y-auto py-6 px-4 md:px-8 lg:px-12"
      >
        <div className="w-full max-w-5xl mx-auto space-y-6">
          {messages.length === 0 && (
            <div className="text-center text-gray-500">
              No messages yet. Start the conversation!
            </div>
          )}
          {messages.map((message) => (
            <React.Fragment key={message._id}>
              <MessageItem message={message} isUser={true}>
                {message.prompt}
              </MessageItem>
              <MessageItem message={message} isUser={false}>
                <ServerMessage
                  message={message}
                  isDriven={drivenIds.has(message._id)}
                  stopStreaming={() => {
                    setIsStreaming(false);
                    focusInput();
                  }}
                  scrollToBottom={scrollToBottom}
                />
              </MessageItem>
            </React.Fragment>
          ))}
          <div ref={messagesEndRef} />
        </div>
      </div>

      <div className="border-t border-gray-200 py-6 px-4 md:px-8 lg:px-12">
        <form
          onSubmit={async (e) => {
            e.preventDefault();
            if (!inputValue.trim()) return;

            setInputValue("");

            const chatId = await sendMessage({
              prompt: inputValue,
            });

            setDrivenIds((prev) => {
              prev.add(chatId);
              return prev;
            });

            setIsStreaming(true);
          }}
          className="w-full max-w-5xl mx-auto"
        >
          <div className="flex items-center gap-3">
            <input
              ref={inputRef}
              value={inputValue}
              onChange={(e) => setInputValue(e.target.value)}
              placeholder="Type your message..."
              disabled={isStreaming}
              className="flex-1 p-4 border border-gray-300 rounded-lg focus:border-blue-500 focus:ring-1 focus:ring-blue-500 outline-none text-base text-black"
            />
            <button
              type="submit"
              disabled={!inputValue.trim() || isStreaming}
              className="px-8 py-4 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors disabled:bg-gray-400 disabled:text-gray-200 font-medium"
            >
              Send
            </button>
            <button
              type="button"
              disabled={messages.length < 2 || isStreaming}
              onClick={() => {
                clearAllMessages();
                setInputValue("");
                setIsStreaming(false);
                focusInput();
              }}
              className="px-8 py-4 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors disabled:bg-gray-400 disabled:text-gray-200 font-medium"
            >
              Clear Chat
            </button>
          </div>
          {isStreaming && (
            <div className="text-xs text-gray-500 mt-2">
              AI is responding...
            </div>
          )}
        </form>
      </div>
    </div>
  );
}

// example-svelte/src/components/ChatWindow.svelte
<script lang="ts">
  import { useQuery, useConvexClient } from "convex-svelte";
  import MessageItem from "./MessageItem.svelte";
  import ServerMessage from "./ServerMessage.svelte";
  import { api } from "../../convex/_generated/api";
  import type { Id } from "../../convex/_generated/dataModel";

  const client = useConvexClient();
  const messages = useQuery(api.messages.listMessages, () => ({}));

  // Use a plain object for better Svelte reactivity tracking
  let drivenIds = $state<Record<string, boolean>>({});
  let isStreaming = $state(false);
  let inputValue = $state("");
  let messagesEndRef = $state<HTMLDivElement | null>(null);
  let inputRef = $state<HTMLInputElement | null>(null);

  function isDriven(id: string): boolean {
    return drivenIds[id] === true;
  }

  function focusInput() {
    inputRef?.focus();
  }

  function scrollToBottom(behavior: ScrollBehavior = "smooth") {
    messagesEndRef?.scrollIntoView({ behavior });
  }

  // Scroll to bottom when window resizes
  $effect(() => {
    function handleResize() {
      scrollToBottom();
    }
    window.addEventListener("resize", handleResize);
    return () => window.removeEventListener("resize", handleResize);
  });

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault();
    if (!inputValue.trim()) return;

    const prompt = inputValue;
    inputValue = "";

    const chatId: Id<"userMessages"> = await client.mutation(
      api.messages.sendMessage,
      { prompt },
    );

    // Use object spread to trigger reactivity
    drivenIds = { ...drivenIds, [chatId]: true };
    isStreaming = true;
  }

  async function clearAllMessages() {
    await client.mutation(api.messages.clearMessages, {});
    inputValue = "";
    isStreaming = false;
    focusInput();
  }

  function stopStreaming() {
    isStreaming = false;
    focusInput();
  }
</script>

<div class="flex-1 flex flex-col h-full bg-white">
  <div class="flex-1 overflow-y-auto py-6 px-4 md:px-8 lg:px-12">
    <div class="w-full max-w-5xl mx-auto space-y-6">
      {#if messages.isLoading}
        <div class="text-center text-gray-500">Loading messages...</div>
      {:else if messages.error}
        <div class="text-center text-red-500">
          Error loading messages: {messages.error.message}
        </div>
      {:else if messages.data && messages.data.length === 0}
        <div class="text-center text-gray-500">
          No messages yet. Start the conversation!
        </div>
      {:else if messages.data}
        {#each messages.data as message (message._id)}
          <MessageItem {message} isUser={true}>
            {message.prompt}
          </MessageItem>
          <MessageItem {message} isUser={false}>
            <ServerMessage
              {message}
              isDriven={isDriven(message._id)}
              {stopStreaming}
              {scrollToBottom}
            />
          </MessageItem>
        {/each}
      {/if}
      <div bind:this={messagesEndRef}></div>
    </div>
  </div>

  <div class="border-t border-gray-200 py-6 px-4 md:px-8 lg:px-12">
    <form onsubmit={handleSubmit} class="w-full max-w-5xl mx-auto">
      <div class="flex items-center gap-3">
        <input
          bind:this={inputRef}
          bind:value={inputValue}
          placeholder="Type your message..."
          disabled={isStreaming}
          class="flex-1 p-4 border border-gray-300 rounded-lg focus:border-blue-500 focus:ring-1 focus:ring-blue-500 outline-none text-base text-black"
        />
        <button
          type="submit"
          disabled={!inputValue.trim() || isStreaming}
          class="px-8 py-4 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors disabled:bg-gray-400 disabled:text-gray-200 font-medium"
        >
          Send
        </button>
        <button
          type="button"
          disabled={!messages.data || messages.data.length < 2 || isStreaming}
          onclick={clearAllMessages}
          class="px-8 py-4 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors disabled:bg-gray-400 disabled:text-gray-200 font-medium"
        >
          Clear Chat
        </button>
      </div>
      {#if isStreaming}
        <div class="text-xs text-gray-500 mt-2">AI is responding...</div>
      {/if}
    </form>
  </div>
</div>
